services:
  - type: web
    name: spring-boot-app
    env: java
    buildCommand: ./mvnw package # Or ./mvnw package if using Maven
    startCommand: java -jar build/libs/your-app-name.jar # Update with your JAR file name
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb+srv://admin:sfqZRLnJgJW0Rczj@cluster0.elzgq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JAVA_OPTS
        value: -Xmx512m

databases:
  - name: mongodb-cloud
    type: external
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://admin:sfqZRLnJgJW0Rczj@cluster0.elzgq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0